### ISSUE TITLE
There is some disagreement in the sources about the name of the project.

### ISSUE THREAD

**Issue by Soliloque** [freenet/pyFreenet#11]
The project is sometime called pyFreenet, sometime lib-pyFreenet, and sometime pyFCP. What is the actual name of this project and should it be uniformised accross the repository? I would change all reference to pyFCP by reference to pyFreenet.

**Comment by Thynix** [comment]
I'm not sure. I think I like `pyFreenet` best? The name of the repo is `lib-pyFreenet` but that can be changed.

**Comment by Soliloque** [comment]
I'll send you a push request with pyFCP and lib-pyFreenet normalised to pyFreenet. I can't do anything about the name of the repo.

**Comment by Thynix** [comment]
I will fix the name of the repo yes.
