### ISSUE TITLE
Dead key in setup.py, line 22

### ISSUE THREAD

**Issue by Soliloque** [freenet/pyFreenet#12]
USK@9X7bw5HD2ufYvJuL3qAVsYZb3KbI9~FyRu68zsw5HVg,lhHkYYluqHi7BcW1UHoVAMcRX7E5FaZjWCOruTspwQQ,AQACAAE/pyfcp-api/0/ is not in Freenet anymore. This key is referenced in setup.py, line 22. Link to the file: https://github.com/freenet/pyFreenet/blame/master/setup.py

Can the  key be reinserted, preferably using pyFreenet-api as the name of the freesite? 

If I understand correctly, this freesite simply contain the directory created by *epydoc -n "pyFreenet API manual" -o html fcp*? If the private key doesn't exist anymore, I'll simply regenerate the documentation and insert it along with a more complete freesite for pyFreenet.

Thanx.

**Comment by Thynix** [comment]
Sure - by all means, feel free to reinsert.
