### ISSUE TITLE
Poor capabilities for resuming jobs

### ISSUE THREAD

**Issue by xloem** [freenet/pyFreenet#17]
Just noting the difficulty accessing jobs from a previous run of the client.
- `FCPNode.jobs` is empty immediately after construction, and I see no way to wait for it to be filled other than sleeping or calling `refreshPersistentRequests`, which is nonintuitive given the documentation stating it is unneeded
- there is no way to set a callback for jobs recovered from the server, which means that job information which is only passed to the callback function and never stored in the ticket is unavailable 

I know the id of the job I am waiting for, so it would be reasonable to say `node.jobs[id] = JobTicket(node, id, '', '')` in advance, but I think this may create a race condition with the existing code.

**Comment by ArneBab** [comment]
hm, yes. I’ll have to check how freesitemgr checks for jobs from a previous run. It’s been a while since I looked at that part, so if you want to check it, feel free to prod the code (fcp/sitemgr.py).

**Comment by ArneBab** [comment]
Race conditions are pretty dangerous here (they can break an existing connection and then both connections die), so I would rather avoid that. Please re-open if this is still an issue.
