### ISSUE TITLE
freesitemgr: site is falsely marked as updated when it is not

### ISSUE THREAD

**Issue by xloem** [freenet/pyFreenet#21]
I had an experience where my site was in the middle of inserting, I updated it and add it again, and the content listed in the config file was updated, but this content was not inserted because an insert was already active.

The result is that after I cancel the existing insert, freesitemgr refuses to begin another, because it finds no changes.

**Comment by ArneBab** [comment]
That’s an existing limitation — you can force the re-insert by opening the datafile in ~/.freesitemgr/SITENAME and removing every entry in files = [
...
]. 

Pull-requests to implement freesitemgr reinsert SITENAME are very welcome!

**Comment by ArneBab** [comment]
There is now a reinsert command. If the site is falsely marked us updating, you need to use `freesitemgr cancel SITENAME`.
