### ISSUE TITLE
Files are not named properly.

### ISSUE THREAD

**Issue by RubyTheRoobster** [freenet/pyFreenet#29]
When cloning the repo, and running ```git checkout 0.4.7```, and then running ```python setup.py install --user```, python will complain about not being able to find ```freesitemgr.py```, as the file is instead named ```freesitemgr```.  This also happens to a bunch of other files.  Please fix this.

**Comment by Thynix** [comment]
Hm, it does seem like there's room for a `bin` directory for scripts without extensions. Does the installation not work, or does it work but print warnings? Why is it important that we fix `0.4.7`?

**Comment by RubyTheRoobster** [comment]
Nevermind.  It seems to magically work now(re-running the same script), and using the most up-to-date version of the branch py3 works.
