### ISSUE TITLE
Clarify License, Is pyFreenet licensed under the LGPL-3.0 or LGPL-2.1

### ISSUE THREAD

**Issue by Destroyinator69420** [freenet/pyFreenet#34]
You did not state which version of the Lesser Gnu Public License pyFreenet is licensed under, so which version is pyFreenet licensed under? I would prefer LGPL-3.0, but I need clarification.

**Comment by ArneBab** [comment]
If there is no license version stated, any version can be used. I would suggest using LGPLv2 **or later** for future changes. That enables the widest re-use without risking future problems.

**Comment by ArneBab** [comment]
This is now clarified: LGPLv2 or later.
